import { Pokemon } from "./pokemon";
import { batalla } from "./Batalla";
import { Tipo } from "./tipo";
const pokemonPlatan = new Pokemon();
const pokemonFuego = new Pokemon();
const pokemoAgua = new Pokemon();
const pokemonNomral = new Pokemon();
const pokemonElectrico = new Pokemon();
const pokemonPsiquico = new Pokemon();
const pokemonLucha = new Pokemon();
const pokemonRoca = new Pokemon(); 
const pokemonTierra = new Pokemon();
const pokemonVolador = new Pokemon();
const pokemonBicho = new Pokemon();
const pokemonVeneno = new Pokemon();
const pokemonSiniestro = new Pokemon();
const pokemonFantasma = new Pokemon();
const pokemonHielo = new Pokemon();
const pokemonAcero = new Pokemon();
const pokemonDragon = new Pokemon();
const pokemonHada = new Pokemon();
const Tipo = new Tipo ();